### ISSUE TITLE
Mistake in the implementation?

### ISSUE THREAD

**Issue by bedax** [nachonavarro/balloon-hashing#1]
On page 7 of [the paper](https://eprint.iacr.org/2016/027.pdf), you can see that `cnt` starts at 0, it is still 0 when it is passed to the first hash function in the expand stage. It is then incremented according to `s_cost`. When `cnt` is used during the mix stage, its value is greater than its initial value.

In this implementation, `cnt` is initialised to 1, a reference is then passed to the expand function. In Python, integers are immutable so when it is incremented a copy is made and that copy is incremented, instead of incrementing the original. When `cnt` is passed to the first hash function in the expand stage, its value is 1. It is then incremented according to `s_cost`, but the accumulated value is thrown away at the end of the expand function, and when `cnt` is passed to `mix`, it is still its initial value.

As `cnt` is used in the security proof this divergence in the implementation should be considered a severe error. I suggest you stop breaking the balloon function up into sub functions, as how Python passes primitives to functions is confusing and is leading to mistakes.

**Comment by nachonavarro** [comment]
Hmm I'm initializing it to 1 because I already pass the hash into the buffer with a `cnt` of 0 on the line before. See line 109.

This:
```python
buf = [hash_func(0, password, salt)]
cnt = 1
expand(buf, cnt, space_cost)
```
is equivalent to their implementation:
```C
buf[0] = hash(cnt++, passwd, salt)
for m from 1 to s_cost-1:
    buf[m] = hash(cnt++, buf[m-1])
```

**Comment by nachonavarro** [comment]
See the update 5e1eb7acf00842

**Comment by bedax** [comment]
Just had a quick look and it looks fine now. You were right about the initial value, btw. Out of interest, did the default values for `time_cost` and `space_cost` come from the paper, or were they just chosen randomly? They seem on the low end to me.

Otherwise, good work, thank you.

**Comment by nachonavarro** [comment]
This was a few years ago, but I believe I took them from the author's [repo](https://github.com/henrycg/balloon/).
